# Generated by Django 4.2.13 on 2024-08-08 01:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prudence", "0003_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="risk",
            name="inherent_impact",
            field=models.IntegerField(
                choices=[
                    (1, "Very Low"),
                    (2, "Low"),
                    (3, "Moderate"),
                    (4, "High"),
                    (5, "Very High"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="risk",
            name="inherent_probability",
            field=models.IntegerField(
                choices=[
                    (1, "Very Low"),
                    (2, "Low"),
                    (3, "Moderate"),
                    (4, "High"),
                    (5, "Very High"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="risk",
            name="inherent_risk_rating",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="risk",
            name="residual_impact",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Very Low"),
                    (2, "Low"),
                    (3, "Moderate"),
                    (4, "High"),
                    (5, "Very High"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="risk",
            name="residual_probability",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Very Low"),
                    (2, "Low"),
                    (3, "Moderate"),
                    (4, "High"),
                    (5, "Very High"),
                ],
                null=True,
            ),
        ),
    ]
