# Generated by Django 4.2.13 on 2024-08-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prudence", "0004_alter_risk_inherent_impact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="control",
            name="effectiveness",
            field=models.FloatField(
                choices=[
                    (0.0, "Not Effective"),
                    (0.5, "Partially Effective"),
                    (1.0, "Fully Effective"),
                ],
                default=0.0,
            ),
        ),
    ]
