# Generated by Django 4.2.13 on 2024-08-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prudence", "0005_alter_control_effectiveness"),
    ]

    operations = [
        migrations.AddField(
            model_name="risk",
            name="last_assessed",
            field=models.DateField(auto_now=True),
        ),
    ]
