# Generated by Django 4.2.13 on 2024-08-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prudence", "0006_risk_last_assessed"),
    ]

    operations = [
        migrations.AddField(
            model_name="control",
            name="clastassessed",
            field=models.DateField(auto_now=True),
        ),
    ]
