# Generated by Django 5.0.6 on 2025-07-14 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prudence', '0011_add_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='risk_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prudence.risktype'),
        ),
    ]
